### ISSUE TITLE
增加用户登录功能

### ISSUE THREAD

**Issue by hmsjy2017** [songwonderful/lan-share#1]
由于可能会涉及隐私问题，希望增加用户登录功能，该功能可关闭

**Comment by songquanpeng** [comment]
我对这个工具定位是用于局域网之间文件的分享，不推荐部署到公网上。至于隐私问题，如果用户比较少的话可以通过加一个 TOKEN 验证来解决，用户需要输入 TOKEN 才能访问网站，这个后续会考虑加上的（目前已经实现的功能是拥有 TOKEN 的用户才能删除文件）。

至于用户登录，这个还要涉及到用户注册以及用户管理（当然也可以使用配置文件来手动增添用户），我目前认为对于本项目来说这个功能不是很必要。

如果你需要的是一个私有云盘，Github 上应该已经有很多较为成熟的项目，可以去找一下哈。
